### ISSUE TITLE
deep-learning-traffic-lights Ask questions 

### ISSUE THREAD

**Issue by yghcats** [davidbrai/deep-learning-traffic-lights#1]
I would like to ask you this project which the data which download: https://github.com/davidbrai/deep-learning-traffic-lights : 
    ~/nexar/images/ \
    ~/nexar/labels_test.txt \
    ~/nexar/lmdb/test_lmdb

Thank you！

**Comment by davidbrai** [comment]
That will be possible if Nexar decide to open source their data set, don't think I can publish it on my own
