### ISSUE TITLE
How long do you need to train your network at g2.2xlarge?

### ISSUE THREAD

**Issue by zsxgb** [davidbrai/deep-learning-traffic-lights#3]
Can you tell me what about you? How long will it take you to train in your network? I would like to estimate how much money I need to spend with AWS.

**Comment by davidbrai** [comment]
Training a single model took a few hours, less than a day, if I remember correctly.

**Comment by zsxgb** [comment]
Thank you very much for your answer. I am very grateful for my wallet

**Comment by davidbrai** [comment]
You're welcome!
