### ISSUE TITLE
how to use notebook in aws

### ISSUE THREAD

**Issue by zsxgb** [davidbrai/deep-learning-traffic-lights#4]
Hello, I used AWS service. There is a problem, would like to ask you again

In my AWS use I used a P2 xlarge, this in my use, aws service staff told me that the use of ssh link to use AWS p2.

There is no way to use jupyter notebook. Do you use the desktop UI? How to use the browser-based jupyter notebook.

If you can be convenient, give me a little share

**Comment by DamonDeng** [comment]
Dear Zsxgb,

To start notebook on AWS EC2, just install jupyter and then start it with the following command:

`jupyter notebook --ip '*' --port 9080 --no-browser`

The number 9080 is the port you want to use, remember to white list it in the security group of your EC2.

Good luck!
