### ISSUE TITLE
Whicth one should I use to Convert to CoreML.

### ISSUE THREAD

**Issue by liuyongVAE** [davidbrai/deep-learning-traffic-lights#7]
I'm a new learner and want to build a  traffic light recognizing app.I want to convert one of your model to CoreML type .But I have no idea which one should I use.
Please forgive my ignorance.Looking forward to your reply!

**Comment by davidbrai** [comment]
Feel free to use any of the models, they will all work well. I used an ensemble of the 3 models together for the competition.

**Comment by liuyongVAE** [comment]
thanks!

**Comment by Tony-Hou** [comment]
I'm sorry for i don't  have the model.




发自网易邮箱大师


在2017年12月21日 20:41，liuyongVAE<notifications@github.com> 写道：

I'm a new learner and want to build a traffic light recognizing app.I want to convert one of your model to CoreML type .But I have no idea which one should I use.
Please forgive my ignorance.Looking forward to your reply!
